<div style="padding-left: 15px; height: 43px; line-height: 43px; color: #ffffff; font-size: 24px; font-weight: bold; background: url(/img/top-ribbon.png);">
	<span>Terms of Use</span>
</div>
<div id="content-wrapper">
<div style="margin-left: auto; margin-right: auto; margin-top: 20px; width: 650px;">
<p>By using this site (the “Site”), you (“you” or the “End User”) agree to the terms and conditions that we (“Chowly”) have provided. If you do not wish to agree to these terms and conditions (the “Terms of Use” or “Agreement”), please refrain from using the Site.</p>
<h3>1. Terms and Conditions for Restaurant-Specific Vouchers.</h3>
<p>For this section, “Restaurant”  shall be defined as a Merchant who offers food and beverage for sale in its regular business operations, and is making such food and beverages available to purchasers of Vouchers.</p>
<p>Redemption frequency is determined by Restaurants, and shall be contained in the Voucher offer on the Site.
Use of Restaurant-Specific Vouchers for alcoholic beverages is at the sole discretion of the Restaurant and is subject to compliance with applicable law
Vouchers cannot be combined with any other restaurant vouchers, third party certificates, coupons, or promotions, unless otherwise specified by Restaurant.
Restaurant-Specific Vouchers cannot be used for taxes, tips or prior balances, unless permitted by the Restaurant.
Valid for dine in only unless otherwise stated.
The issuing of restaurant credit is at the sole discretion of the Restaurant unless otherwise required by applicable law.
Neither Chowly nor the Restaurant is responsible for lost or stolen Vouchers or restaurant Voucher reference numbers.
Reproduction, sale or trade of a Restaurant-Specific Voucher is prohibited unless done so in compliance with applicable law.
Any attempted redemption not consistent with these terms &amp; conditions will render the Restaurant-Specific Voucher void.
Void to the extent prohibited by law.
If you redeem the Voucher for less than its face value, you will only be entitled to a credit or cash from the Restaurant, equal to the difference between the face value and the amount you redeemed, if required by applicable law. You will only be entitled to a continuing redemption value as noted above if the amount that you paid for the Voucher exceeds the amount you redeemed. For example, if you paid $20 for a Voucher which entitles you to purchase $50 of product by February 1, 2010 and you make a purchase for $40 on January 30, 2010, you will only be entitled to a credit or cash equal to the difference between the $50 face value and the amount you redeemed from the Merchant (i.e., $10) if required by applicable law. You will not have any redemption value either because the amount you redeemed is more than what you paid for the Voucher.
All purchases of Vouchers for Restaurants may have statutory limitations on the amount of the Voucher value that can be redeemed for alcoholic beverages. Chowly’s sole role in the transaction is as a marketing agent for the Merchant Voucher, and the applicability and compliance with any relevant statute or code is solely determined and consummated by the Merchant, and Chowly has no role in such determination or action on the part of the Merchant.
All Vouchers shall be subject to the terms and conditions of Chowly and the participating Restaurant or Merchant. The Merchant or Restaurant are the sellers of the goods or services which you are purchasing.
</p>
<p>The holder and issuer of a Restaurant-Specific Voucher is the Restaurant. The holder and issuer of a Merchant Voucher is the Merchant. As a holder and issuer of the Voucher, the Restaurant or Merchant shall be fully responsible for any and all injuries, illnesses, damages, claims, liabilities and costs suffered by or in respect of a customer, caused in whole or in part by the Restaurant or the Merchant, as well as for any unclaimed property liability arising from unredeemed Vouchers or portions thereof. You waive, and release Chowly and its officers, directors, employees and agents from, any claim, liabilities, damages, or injury arising from or related to any act or omission of Merchant or Restaurant in connection with a Voucher or the services/goods provided in connection therewith and/or as it relates to compliance with applicable unclaimed property and other laws relating to the redemption of the Vouchers or any portion thereof. Restaurant-Specific Vouchers and Merchant Vouchers are redeemable in their entirety and on a one time basis only and may not be redeemed incrementally.</p>
<p>According to applicable law, the Merchant may be responsible for allowing you to redeem your Voucher for the cash value based on the money you actually paid for your Voucher (i.e. if you paid $20 for a Voucher which gives you $50 of value to the Merchant, the cash value that you paid is $20, not $50), for a period of time that extends beyond the expiration date on the Voucher. While the expiration date on the Voucher dictates the last date that you can use your Voucher at Merchant for the promotional offer stated on the Chowly, applicable law may provide that the Merchant is responsible for honoring the cash value that you paid for your Voucher for a period of time beyond the expiration date stated on the Voucher. In other words, you should be allowed to redeem the cash value (or purchase price) of your Voucher up until the greater of: (1) the Voucher’s expiration date; or (2) the minimum length of time allowed by applicable law for a Voucher to expire. In the event that you have an expired Voucher and would like to redeem it for the price you paid to acquire it, please contact the Merchant. Once again, the Merchant should allow such redemption if applicable law requires it, and we have instructed the Merchant to do so. If you have gone to the Merchant and the Merchant has refused to redeem the cash value of your expired Voucher, and if applicable law entitles you to such redemption, then please contact Chowly [and explain your situation in writing] and Chowly will refund the purchase price of the Voucher in either Canadian Dollars or credit for purchases of future Vouchers from Chowly.</p>

<h2>TERMS OF USE</h2>

<h3>1. General.</h3>

<p>The Site provides an interactive online service operated by Chowly, Corp. on the World Wide Web of the Internet (the “Web”), consisting of information services, content and transaction capabilities facilitated through Chowly, affiliates of Chowly or merchants (“Merchants”) offering vouchers for sale (“Vouchers”) which may be exchanged for goods/services at Merchants and other third parties.</p>

<p>This Agreement sets forth the terms and conditions that apply to the use of this Site by the End User. By using this Site (other than to read this Agreement for the first time), End User agrees to comply with all of the terms and conditions hereof. The right to use this Site is personal to End User and is not transferable to any other person or entity. End User shall be responsible for protecting the confidentiality of End User’s password(s), if any. End User acknowledges that, although the Internet is often a secure environment, sometimes there are interruptions in service or events that are beyond the control of Chowly, and Chowly shall not be responsible for any data lost while transmitting information on the Internet. While it is Chowly’s objective is to make the Site accessible 24 hours per day, 7 days per week, the Site may be unavailable from time to time for any reason including, without limitation, routine maintenance. You understand and acknowledge that due to circumstances both within and outside of the control of Chowly, access to the Site may be interrupted, suspended or terminated from time to time.</p>
<p>Chowly shall have the right at any time to change or discontinue any aspect or feature of the Site, including, but not limited to, content, hours of availability and equipment needed for access or use. Further, Chowly may discontinue disseminating any portion of information or category of information, may change or eliminate any transmission method and may change transmission speeds or other signal characteristics.</p>
<p>You represent that you are of legal age to form a binding contract. You must be at least 18 years old to be eligible to use the Site. However, if you are at least 13 years old but not yet 18, you may use the Site in conjunction with your parent or guardian who agrees to this Agreement. No one under age 13 may use the Site.</p>

<h3>2. Modified Terms.</h3>

<p>Chowly reserves the right at all times to discontinue or modify any of our Terms of Use and/or our Privacy Policy as we deem necessary or desirable. Such changes may include, among other things, the adding of certain fees or charges. If Chowly makes any substantial changes, we will notify you by sending you an e-mail to the e-mail address that is registered with your account and/or by posting notice of the change on the Site. Any changes to these Terms of Use will be effective upon the earlier of our dispatch of an e-mail notice to you or our posting of notice of the changes on our Site, provided that these changes will not apply to Vouchers purchased prior to the effective date of such changes. These changes will be effective immediately for new users of our Site and any Vouchers purchased by such new users. We suggest to you, therefore, that you re-read this important notice containing our Terms of Use and Privacy Policy from time to time in order that you stay informed as to any such changes. Any use of the Site by End User after such notice shall be deemed to constitute acceptance by End User of such modifications.</p>

<h3>3. Equipment.</h3>

<p>End User shall be responsible for obtaining and maintaining all telephone, computer hardware and other equipment needed for access to and use of this Site and all charges related thereto. Chowly shall not be liable for any damages to the End User’s equipment resulting from the use of this Site.</p>

<h3>4. End User Conduct.</h3>

<p>This Site and any individual sites or merchant-specific, city-specific, or province-specific sites now or hereinafter contained within or otherwise available through external hyperlinks with our Site (the “Microsites”) are private property. All interactions on this Site and/or the Microsites must comply with these Terms of Use. Although we welcome and encourage user interaction on our Site, we do insist and require that all end users restrict any and all activity in connection with the use of this Site and the Microsites to that which involves lawful purposes only. End User shall not post or transmit through this Site any material which violates or infringes in any way upon the rights of others, or any material which is unlawful, threatening, abusive, defamatory, invasive of privacy or publicity rights, vulgar, obscene, profane or otherwise objectionable, which encourages conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any law, or which, without Chowly’s express prior, written approval, contains advertising or any solicitation with respect to products or services. Any conduct by an End User that in Chowly’s exclusive discretion restricts or inhibits any other End User from using or enjoying this Site and/or any of the Microsites is strictly prohibited. End User shall not use this Site or any of the Microsites to advertise or perform any commercial, religious, political or non-commercial solicitation, including, but not limited to, the solicitation of users of this Site and/or the Microsites to become users of other on- or offline services directly or indirectly competitive or potentially competitive with Chowly.</p>

<p>The foregoing provisions of this Section 4 apply equally to and are for the benefit of Chowly, its subsidiaries, affiliates, Merchants and its third-party content providers and licensors, and each shall have the right to assert and enforce such provisions directly or on its own behalf.</p>

<h3>5. Copyright and Trademarks.</h3>

<p>Everything located on or in this Site, including the Microsites, is the exclusive property of Chowly, Corp. or used with express permission of the copyright and/or trademark owner. ANY COPYING, DISTRIBUTING, TRANSMITTING, POSTING, LINKING, DEEP LINKING, OR OTHERWISE MODIFYING OF THIS SITE OR ANY OF THE MICROSITES WITHOUT THE EXPRESS WRITTEN PERMISSION OF CHOWLY, CORP. IS STRICTLY PROHIBITED. Any violation of this policy may result in a copyright, trademark or other intellectual property right infringement that may subject End User to civil and/or criminal penalties.</p>

<p>This Site and any Microsites contain copyrighted material, trademarks and other proprietary information, including, but not limited to, text, software, photos, video, graphics, music and sound, and the entire contents of the Site are protected by copyright as a collective work under the Canadian copyright laws. Chowly owns a copyright in the selection, coordination, arrangement and enhancement of such content, as well as in the content original to it. End User may not modify, publish, transmit, participate in the transfer or sale, create derivative works, or in any way exploit any of the content, in whole or in part. End User may download, print, and/or save copyrighted material for End User’s personal use only. Except as otherwise expressly stated under copyright law, no copying, redistribution, retransmission, publication or commercial exploitation of downloaded material without the express permission of Chowly or the copyright owner is permitted. If copying, redistribution or publication of copyrighted material is permitted, no changes in or deletion of author attribution, trademark legend or copyright notice shall be made. End User acknowledges that he/she/it does not acquire any ownership rights by downloading copyrighted material. Trademarks that are located within or on the Site or a Microsite otherwise owned or operated in conjunction with Chowly shall not be deemed to be in the public domain but rather the exclusive property of Chowly, unless such site is under license from the Trademark owner thereof, in which case such license is for the exclusive benefit and use of Chowly unless otherwise stated.</p>

<p>End User shall not upload, post or otherwise make available on this Site any material protected by copyright, trademark or other proprietary right without the express permission of the owner of the copyright, trademark or other proprietary right. Chowly does not have any express burden or responsibility to provide End User with indications, markings or anything else that may aid End User in determining whether the material in question is copyrighted or trademarked. End User shall be solely liable for any damage resulting from any infringement of copyrights, trademarks, proprietary rights or any other harm resulting from such a submission. By submitting material to any public area of this Site or any Microsite, End User warrants that the owner of such material has expressly granted Chowly the royalty-free, perpetual, irrevocable, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate and distribute such material (in whole or in part) worldwide and/or to incorporate it in other works in any form, media or technology now known or hereafter developed for the full term of any copyright that may exist in such material. End User also permits any other end user to access, view, store or reproduce the material for that End User’s personal use. End User hereby grants Chowly the right to edit, copy, publish and distribute any material made available on this Site or any Microsite by End User.</p>

<p>The foregoing provisions of Section 5 apply equally to and are for the benefit of Chowly, its subsidiaries, affiliates, Merchants and its third party content providers and licensors and each shall have the right to assert and enforce such provisions directly or on its own behalf.</p>

<h3>6. Copyright Policy.</h3>

<p>Chowly reserves the right to terminate its agreement with any End User who repeatedly infringes third-party copyright rights upon prompt notification to Chowly by the copyright owner or the copyright owner’s legal agent. Without limiting the foregoing, if you believe that a copyrighted work has been copied and posted via the Site or any Microsite in a way that constitutes copyright infringement, you shall provide Chowly with the following information: (a) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyrighted work; (b) an identification and location on the Site or any Microsite of the copyrighted work that you claim has been infringed; (c) a written statement by you that you have a good faith belief that the disputed use is not authorized by the owner, its agent, or the law; (d) your name and contact information, such as telephone number or e-mail address; and (e) a statement by you that the above information in your notice is accurate and, under penalty of perjury, that you are the copyright owner or authorized to act on the copyright owner’s behalf. Contact information for Chowly’s Copyright Agent for notice of claims of copyright infringement is as follows:</p>
<pre>
Chowly, Corp. 
Attn: Copyright Agent 
40 The Driveway 
Suite 1501 
Ottawa, ON K2P  2C9 
Copyright@Chowly.com
</pre>

<h3>7. Disclaimer of Warranty.</h3>

<p>END USER EXPRESSLY AGREES THAT USE OF THIS SITE AND THE MICROSITES IS AT END USER’S SOLE RISK. NEITHER CHOWLY, ITS AFFILIATES NOR ANY OF THEIR RESPECTIVE EMPLOYEES, AGENTS, MERCHANTS, THIRD-PARTY CONTENT PROVIDERS OR LICENSORS, OR ANY OF THEIR OFFICERS, DIRECTORS, EMPLOYEES OR AGENTS, WARRANT THAT USE OF THE SITE OR ANY MICROSITE WILL BE UNINTERRUPTED OR ERROR FREE; NOR DO THEY MAKE ANY WARRANTY AS TO (I) THE RESULTS THAT MAY BE OBTAINED FROM USE OF THIS SITE, OR ANY MICROSITE, OR (II) THE ACCURACY, RELIABILITY OR CONTENT OF ANY INFORMATION, SERVICE OR VOUCHERS PROVIDED THROUGH THIS SITE OR THE MICROSITES.</p>

<p>THIS SITE AND THE MICROSITES ARE MADE ACCESSIBLE ON AN “AS IS” AND “AS AVAILABLE”  BASIS. CHOWLY HEREBY DISCLAIMS ANY AND ALL REPRESENTATIONS, WARRANTIES AND CONDITIONS, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THOSE OF TITLE NONINFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE.</p>

<h3>8. Limitation of Liability.</h3>

<p>IN NO EVENT SHALL CHOWLY, BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO THIS AGREEMENT. IN NO EVENT WILL CHOWLY’S LIABILITY IN CONNECTION WITH A CHOWLY EXCEED THE AMOUNTS PAID FOR SUCH CHOWLY, AND TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT SHALL NOT EXCEED THE AMOUNTS PAID BY END USER DURING THE SIX MONTHS PRECEDING THE BRINGING OF ANY CLAIM.</p>

<h3>9. Monitoring.</h3>

<p>Chowly shall have the right, but not the obligation, to monitor the content of the Site and any Microsites at all times, including any chat rooms and forums that may hereinafter be included as part of the Site, to determine compliance with this Agreement and any operating rules established by Chowly, as well as to satisfy any applicable law, regulation or authorized government request. Without limiting the foregoing, Chowly shall have the right, but not the obligation, to remove any material that Chowly, in its sole discretion, finds to be in violation of the provisions hereof or otherwise objectionable.</p>

<h3>10. Privacy.</h3>

<p>End User acknowledges that all discussion for ratings, comments, bulletin board service, chat rooms and/or other message or communication facilities (collectively “Communities”) are public and not private communications, and that, therefore, others may read End User’s communications without End User’s knowledge. Chowly does not control or endorse the content, messages or information found in any Community, and, therefore, Chowly specifically disclaims any liability concerning the Communities and any actions resulting from End Users’ participation in any Community, including any objectionable content. Generally, any communication which End User posts to Chowly (whether in chat rooms, discussion groups, message boards or otherwise) is considered to be non-confidential. If particular web pages permit the submission of communications that will be treated by Chowly as confidential, that fact will be stated on those pages. By posting comments, messages or other information on the Site or any Microsite, End User grants Chowly the right to use such comments, messages or information for promotions, advertising, market research or any other lawful purpose without territorial, time or other limitation. For more information see Chowly’s Privacy Policy.</p>

<h3>11. License Grant.</h3>

<p>By posting communications on or through this Site or any Microsite, End User shall be deemed to have granted to Chowly a royalty-free, perpetual, irrevocable, non-exclusive license to use, reproduce, modify, publish, edit, translate, distribute, perform, and display the communication alone or as part of other works in any form, media, or technology whether now known or hereafter developed without territorial or time limitations, and to sublicense such rights through multiple tiers of sublicensees.</p>

<h3>12. Indemnification/Release.</h3>

<p>End User agrees to defend, indemnify and hold harmless Chowly, its affiliates and their respective directors, officers, employees and agents from and against all claims and expenses, including attorneys’ fees, arising out of or related to any products or services purchased by End User in connection with the Site or any Microsites.</p>

<p>End User is solely responsible for interactions with Merchants and other users of the Site or Microsites. To the extent permitted under applicable laws, End User hereby releases Chowly from any and all claims or liability related to any product or service of a Merchant, any action or in-action by Merchant, including Merchant’s failure to comply with applicable law and/or failure to abide by the terms of a Voucher, and any conduct or speech, whether online or offline, of any other user.</p>

<h3>13. Termination.</h3>

<p>Chowly may terminate this Agreement at any time. Without limiting the foregoing, Chowly shall have the right to immediately terminate or suspend any passwords or accounts of End User in the event of any conduct by End User or which Chowly, in its sole discretion, considers to be unacceptable, or in the event of any breach by End User of this Agreement. The provisions of Sections 2, 4, 5, 6, 7, 10, 11, and 12 will survive termination of this Agreement.”</p>

<h3>14. Trademarks.</h3>

<p>Chowly is a trademark of Chowly, Corp. All rights in respect of this trademark are hereby expressly reserved. Unless otherwise indicated, all other trademarks appearing on Chowly are the property of their respective owners.</p>

<h3>15. Third-Party Content.</h3>

<p>Chowly, similar to an Internet Service Provider, is a distributor (and not a publisher) of content supplied by third parties and End Users. Accordingly, Chowly has no more editorial control over such content than does a public library, bookstore or newsstand. Any opinions, advice, statements, services, offers, or other information or content expressed or made available by third parties, including information providers, or any other end users are those of the respective author(s) or distributor(s) and not of Chowly.</p>

<p>In many instances, the content available through this Site represents the opinions and judgments of the respective information provider, end user, or other user not under contract with Chowly. Chowly neither endorses nor is responsible for the accuracy or reliability of any opinion, advice, or statement made on Chowly by anyone other than authorized Chowly employee spokespersons while acting in official capacities. Under no circumstances will Chowly be liable for any loss or damage caused by an end user’s reliance on information obtained through Chowly. It is the responsibility of End User to evaluate the accuracy, completeness, or usefulness of any information, opinion, advice, etc., or other content available through Chowly.</p>

<p>Chowly contains links to third-party websites maintained by other content providers. These links are provided solely as a convenience to you and not as an endorsement by Chowly of the contents on such third-party sites, and Chowly hereby expressly disclaims any representations regarding the content or accuracy of materials on such third-party websites. If End User decides to access linked third-party websites, End User does so at its own risk. Unless you have executed a written agreement with Chowly expressly permitting you to do so, you may not provide a hyperlink to the Site or any Microsite from any other website. Chowly reserves the right to revoke its consent to any link at any time in its sole discretion.</p>

<h3>16. Miscellaneous.</h3>

<p>This Agreement, including the Terms of Sale set forth below (which are incorporated into this Agreement), and any operating rules for Chowly established by Chowly, constitute the entire agreement of the parties with respect to the subject matter hereof. No waiver by either party of any breach or default hereunder is a waiver of any preceding or subsequent breach or default. The section headings used herein are for convenience only and shall be of no legal force or effect. If any provision of this Agreement is held invalid by a court of competent jurisdiction, such invalidity shall not affect the enforceability of any other provisions contained in this Agreement, and the remaining portions of this Agreement shall continue in full force and effect. The failure of either party to exercise any of its rights under this Agreement shall not be deemed a waiver or forfeiture of such rights or any other rights provided hereunder.</p>

<h3>17. Arbitration.</h3>

<p>By using this Site, End User agrees that: (1) any claim, dispute, or controversy End User may have against Chowly arising out of, relating to, or connected in any way with this Agreement, this Site, or any Microsite, or the purchase or sale of any Voucher(s), shall be resolved exclusively by final and binding arbitration administered by the arbitration group or groups selected by Chowly; (2) the arbitration shall be held at a location determined by Chowly (provided that such location is reasonably convenient for End User (3) the arbitrator shall apply Ontario law, and shall honor claims of privilege recognized at law; (4) there shall be no authority for any claims to be arbitrated on a class or representative basis; arbitration can decide only the End User’s and/or Chowly’s individual claims; and the arbitrator may not consolidate or join the claims of other persons or parties who may be similarly situated; (5) in the event that the End User is able to demonstrate that the costs of arbitration will be prohibitive as compared to the costs of litigation, Chowly will pay as much of the End User’s filing and hearing fees in connection with the arbitration as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive; and (6) with the exception of subpart (4) above, if any part of this arbitration provision is deemed to be invalid, unenforceable or illegal, or otherwise conflicts with Ontario law, then the balance of this arbitration provision shall remain in effect and shall be construed in accordance with its terms as if the invalid, unenforceable, illegal or conflicting provision were not contained herein. If, however, subpart (4) is found to be invalid, unenforceable or illegal, then the entirety of this Arbitration Provision shall be null and void, and neither End User nor Chowly shall be entitled to arbitrate their dispute.</p>

<h3>18. Disclosures.</h3>

<p>Chowly is located at 40 The Driveway, Suite 1501, Ottawa, ON K2P 2C9.</p>

<h3>II.TERMS OF SALE</h3>

<p>All vouchers printed from the Site or any Microsite, or any other website associated with Chowly (hereinafter “Vouchers”) are promotional vouchers that may be purchased from participating merchants (“Merchants”) through Chowly to be used in exchange for goods and services at a discount from their actual cost. By placing an order for a Voucher from a Merchant through Chowly, you make an offer to purchase the Vouchers you have selected on the terms and conditions stated below. You may be required to create an account in order to purchase any Voucher. This may be required so we can provide you with easy access to print your orders, view your past purchases, modify your preferences, and to ensure permissible use of the Voucher.</p>

<p>The Voucher you purchase through Chowly is redeemable for goods or services by the Merchant. The Merchant, not Chowly, is the seller of the Voucher and the goods and services and is solely responsible for redeeming any Voucher you purchase. Chowly sells a Voucher that can be redeemed in connection with your purchase of the goods or services from Merchant</p>
</div>
<br />
</div>